import type { Metadata } from "next";
import { Navbar } from "@/components/Navbar";
import { VideoPlayer } from "@/components/VideoPlayer";
import { Providers } from "./providers";
import { Player } from "@/components/Player";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="min-h-dvh bg-black text-white">
          <Navbar />
          <VideoPlayer />
          <div className="content-wrapper relative z-5 px-40 pt-40">
            <Providers>
              {children}
              <Player/>
            </Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
